service: gc-serverless-template

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: europe-west1
  project: fasteating
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  myFunction:
    handler: myFunction
    events:
      - http: path
